changes

diff --git a/.config/i3/scripts/openweather-city b/.config/i3/scripts/openweather-city
--- a/.config/i3/scripts/openweather-city
+++ b/.config/i3/scripts/openweather-city
@@ -1,43 +1,55 @@
 #!/usr/bin/env bash
 
-command -v jq >/dev/null 2>&1 || { echo >&2 "Program 'jq' required but it is not installed.
-Aborting."; exit 1; }
-command -v curl >/dev/null 2>&1 || { echo >&2 "Program 'curl' required but is not installed.
-Aborting."; exit 1; }
+command -v jq >/dev/null 2>&1 || {
+	echo >&2 "Program 'jq' required but it is not installed. Aborting."
+	exit 1
+}
+command -v curl >/dev/null 2>&1 || {
+	echo >&2 "Program 'curl' required but is not installed. Aborting."
+	exit 1
+}
 
-# To use this script you need to create an API key here https://home.openweathermap.org
-# You need to put your Open Weather APIKEY here:
-APIKEY="keykey"
-# find your City ID here: https://openweathermap.org/
-# search for your city and copy the ID from the URL inside the browser.
-CITY_ID="idid"
+# OpenWeather API key (replace with your actual API key)
+APIKEY="cbba78fc1595a2610671185490bb3ad3"
+
+# Paramakudi City ID (ID for Paramakudi)
+CITY_ID="1260309"
+
+# URL to fetch the weather data
 URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&units=metric&APPID=${APIKEY}"
 
-WEATHER_RESPONSE=$(timeout --signal=1 2s curl -s "${URL}") ||  exit 1;
+# Fetch the weather data
+WEATHER_RESPONSE=$(timeout --signal=1 2s curl -s "${URL}") || exit 1
 
+# Parse weather information
 WEATHER_CONDITION=$(echo $WEATHER_RESPONSE | jq '.weather[0].main' | sed 's/"//g')
 WEATHER_TEMP=$(echo $WEATHER_RESPONSE | jq '.main.temp')
-WIND_DIR=$( echo "$WEATHER_RESPONSE" | jq '.wind.deg')
-WIND_SPEED=$( echo "$WEATHER_RESPONSE" | jq '.wind.speed')
+WIND_DIR=$(echo "$WEATHER_RESPONSE" | jq '.wind.deg')
+WIND_SPEED=$(echo "$WEATHER_RESPONSE" | jq '.wind.speed')
 
+# Calculate wind speed in km/h
 WIND_SPEED=$(awk "BEGIN {print 60*60*$WIND_SPEED/1000}")
+
+# Calculate wind direction
 WIND_DIR=$(awk "BEGIN {print int(($WIND_DIR % 360)/22.5)}")
-DIR_ARRAY=( N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N )
+DIR_ARRAY=(N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N)
 WIND_DIR=${DIR_ARRAY[WIND_DIR]}
 
+# Set appropriate weather icon
 case $WEATHER_CONDITION in
-  'Clouds')
-    WEATHER_ICON=""
-    ;;
-  'Rain')
-    WEATHER_ICON=""
-    ;;
-  'Snow')
-    WEATHER_ICON=""
-    ;;
-  *)
-    WEATHER_ICON=""
-    ;;
+'Clouds')
+	WEATHER_ICON=""
+	;;
+'Rain')
+	WEATHER_ICON=""
+	;;
+'Snow')
+	WEATHER_ICON=""
+	;;
+*)
+	WEATHER_ICON=""
+	;;
 esac
 
+# Output the weather information
 echo "${WEATHER_ICON}  ${WEATHER_TEMP}°C: ${WIND_SPEED} km/h ${WIND_DIR}"
